package:
  name: torchplus
  version: 0.0.5

source:
  path: C:\Users\zhang\Documents\GitHub\torchplus

build:
  number: 1

requirements:
  build:
    - python
  run:
    - python
    - pillow
    - numpy
    - pytorch
    - torchvision
about:
  summary: Torchplus is a utilities library that extends pytorch and torchvision
  home: https://github.com/zhangzp9970/torchplus
  license: GPL-v3