package:
  name: torchplus
  version: 0.0.8

source:
  path: ./

build:
  noarch: python
  number: 3

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pillow
    - numpy
    - pytorch
    - torchvision
    - tensorboard
about:
  summary: Torchplus is a utilities library that extends pytorch and torchvision
  home: https://github.com/zhangzp9970/torchplus
  license: GPL-v3