package:
  name: torchplus
  version: 0.1.0

source:
  path: ./

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  include_recipe: False
  noarch: python
  number: 1

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.8
    - pillow
    - numpy
    - pytorch >=1.10.1
    - torchvision>=0.11.2
    - tensorboard
about:
  summary: Torchplus is a utilities library that extends PyTorch
  home: https://github.com/zhangzp9970/torchplus
  license: GPL-v3